/*
This select shows the list of the place unvailable on a trip

 id_reservation | date_reservation | en_ligne | numero_place | id_client | id_voyage | id_receptionniste
----------------+------------------+----------+--------------+-----------+-----------+-------------------
           5621 | 2022-04-11       | t        |            1 |       767 |       586 |                23
           4024 | 2022-06-19       | f        |            5 |       731 |       586 |                13
          10258 | 2022-01-23       | t        |            5 |       899 |       586 |                14
           5091 | 2022-01-18       | f        |            9 |       462 |       586 |                18
          12007 | 2022-06-18       | f        |           10 |       758 |       586 |                33
           9047 | 2022-01-27       | f        |           11 |       987 |       586 |                 4
             10 | 2022-03-21       | f        |           12 |       883 |       586 |                25
           9251 | 2021-12-16       | t        |           14 |       388 |       586 |                11
           4986 | 2022-01-27       | f        |           14 |       559 |       586 |                11
           7822 | 2022-01-25       | f        |           15 |       557 |       586 |                23
(10 rows)

PS: The values on the table are not accurate because of
the random values generated by Mockaroo

However the request we use is one of the ways to find an available
place on a trip
*/

select * 
from reservation 
where id_voyage = 586
order by numero_place;
